

fx_version 'bodacious'
games {'gta5'}
this_is_a_map 'yes'
lua54 'yes'
files {
    "stream/*",
}
data_file 'DLC_ITYP_REQUEST' 'stream/pokemonpsyduck.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Maca_verdesaborosa.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Maca_vermelhasaborosa.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_PocaoBlue.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_PocaoGreen.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_PocaoPink.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_PocaoRoxa.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bulbasaur.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/charmander.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/chikorita.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Cinnamoroll.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/eevenplush.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/emolga.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Kitty_badtzmaru.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Kitty_MyMelody.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/meowth.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_caixapokemon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Corsola.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Dragonita.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Dratini.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Jigglypuff.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Lapras.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Magikarp.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Mudkip.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Piplup.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_pokebola.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_pokebola2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_ShellosEast.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_ShellosWest.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Totodile.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Whiscash.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/pikachu.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/PikachuFeliz.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/pochacco.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/pompompurin.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/squirtle.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/pokemonpsyduck.ytyp'
dependency '/assetpacks'