

fx_version "bodacious"
lua54 'yes'
version '1.0'
games {"gta5"}
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_JuiceDefrutas.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_JuiceDemaca.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_JuiceDeuva.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_leitebanana.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_leitechocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_leitemorango.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Sucodekiwi.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_sucodelimao2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_sucodemorango.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_sucodlaranja.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Yakultmaca.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_bolomorango.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_cereais.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_churros.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_danone.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_docedemorango.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_iogutemaça.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_iogutemorango.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_pudimduva.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_tortaamendoin.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_batatacro.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_empanadofrango.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_frangofrito.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_hotcorean.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Xbacon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_xegburguer.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_AlaniFitShake.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Batidadechocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Batidademorango.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Cafecomchocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_Soda.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_sucolimao22.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_abacateovos.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_bibimbap.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_bifeepao.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_bolocarne.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_caviarvermelho.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_eggsbenedict.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_mexilhoes.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_peixebatata.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_purebatata.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_salada.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_salmaomolho.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_sanduichefrutos.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_wafflesgelado.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_coquetelcarambola.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_coquetellaranjaelimao.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_daiquiridemorango.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_leitedecoco.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_limonada.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_mangaelimao.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_morangoemanga.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_morangoepesego.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/Mia_uvalimao.ytyp'
dependency '/assetpacks'